name: WaifuHub
description: The WaifuHub Mobile App.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.7.2
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/img/icons/ic_likes.png
    - assets/img/icons/ic_comments.png
    - assets/img/waifu1.png
    - assets/img/waifu2.png
    - assets/img/waifu3.png
    - assets/img/waifu4.png
    - assets/img/waifu5.png
    - assets/img/icons/launcher_icon.png
    - assets/img/icons/ic_login.png

flutter_icons:
  image_path: "assets/img/icons/launcher_icon.png"
  android: true
  ios: true