blank_issues_enabled: false
contact_links:
  - name: WaifuHub Discord
    url: https://discord.gg/Fbj4usA
    about: Please communicate in this server.
  - name: WaifuHub Email
    url: waifuhub.team@gmail.com
    about: If you can not get in touch via email.
